### ISSUE TITLE
Wrong "API_URL"?

### ISSUE THREAD

**Issue by zdhNarsil** [quantmew/okex-py#2]
Should `API_URL` in `const.py` be changed to okex.win instead of okex.com ?

 I will get `HTTPSConnectionPool(host='www.okex.com', port=443)` when using the latter address.

**Comment by jstzwj** [comment]
The website `www.okex.com` is blocked in China Mainland. I will add methods to modify API_URL and PROXY in the API client later.

**Comment by jstzwj** [comment]
The example of changing api_url: https://github.com/quantmew/okex-py/blob/main/example_v5.py#L36
