### ISSUE TITLE
运行run.py报错

### ISSUE THREAD

**Issue by jackandres** [quantmew/okex-py#3]
运行的时候有报错，报FileNotFoundError: [Errno 2] No such file or directory: 'api.json'

**Comment by jstzwj** [comment]
需要在根目录新建文件api.json，其中填写你的'api_key', 'secret_key'和'passphrase'信息

**Comment by jackandres** [comment]
哦，原来是这样的，好的，谢谢！！


***@***.***
 
发件人： WangJun
发送时间： 2021-08-30 20:22
收件人： quantmew/okex-py
抄送： jackandres; Author
主题： Re: [quantmew/okex-py] 运行run.py报错 (#3)
需要在根目录新建文件api.json，其中填写你的'api_key', 'secret_key'和'passphrase'信息
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jackandres** [comment]
你好，
         不好意思，还有一个问题，就是运行run.py这个程序的时候，一直报识别不到okex模块的问题，

但是我看一下每个目录下都有那个_init_.py这个文件的，能帮忙看一下吗？谢谢！！！



***@***.***
 
发件人： WangJun
发送时间： 2021-08-30 20:22
收件人： quantmew/okex-py
抄送： jackandres; Author
主题： Re: [quantmew/okex-py] 运行run.py报错 (#3)
需要在根目录新建文件api.json，其中填写你的'api_key', 'secret_key'和'passphrase'信息
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jstzwj** [comment]
你需要`pip install .`安装后再运行，或者在run.py中添加
```
import sys
import os
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), '../'))
)
```
将上级目录的包添加到python环境中。

**Comment by ArmanAzadi** [comment]
Dear,
would you please support solving " FileNotFoundError: [Errno 2] No such file or directory: 'api.json'" error, thanks.
I created an empty api.json file in the code directory but another error has occurred. 
It would be appreciated if you support me, thanks.
